import Vue from "vue";
import {
    Icon,
    Tab,
    Tabs,
    List,
    Cell,
    Button,
    Popup,
    Field,
    Dialog,
    Toast,
    Swipe,
    SwipeItem,
    Area,
    NavBar,
    CellGroup,
    Image,
    Sticky,
    Grid,
    GridItem,
    Col,
    Row,
    RadioGroup,
    Radio,
    Checkbox,
    CheckboxGroup,
    ActionSheet,
    Calendar,
    Uploader,
    Tag,
    DropdownMenu,
    DropdownItem,
    Picker,
    Form,
    Search,
    DatetimePicker
} from "vant";


Vue.use(Icon);
Vue.use(Tab);
Vue.use(Search);
Vue.use(Tabs);
Vue.use(List);
Vue.use(Cell);
Vue.use(Button);
Vue.use(Popup);
Vue.use(Field);
Vue.use(Dialog);
Vue.use(Toast);
Vue.use(Swipe);
Vue.use(SwipeItem);
Vue.use(Area);
Vue.use(NavBar);
Vue.use(CellGroup);
Vue.use(Image);
Vue.use(Sticky);
Vue.use(Grid);
Vue.use(GridItem);
Vue.use(Col);
Vue.use(Row);
Vue.use(RadioGroup);
Vue.use(Radio);
Vue.use(Checkbox);
Vue.use(CheckboxGroup);
Vue.use(ActionSheet);
Vue.use(Calendar);
Vue.use(Tag);
Vue.use(Uploader);
Vue.use(DropdownMenu);
Vue.use(DropdownItem);
Vue.use(Picker);
Vue.use(Form);
Vue.use(DatetimePicker);